services:
  gemini-bot:
    container_name: gemini-bot
    build:
      context: .
    restart: unless-stopped
    depends_on:
      - db
    dns: 1.1.1.1
    env_file:
      - .env
    volumes:
      - ./data/bot:/data
      - ./data/cache:/cache
      - ./data/logs:/logs
    tty: true

  db:
    container_name: gemini-postgres
    image: postgres:16-alpine
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data/db:/var/lib/postgresql/data