services:
  gemini-bot:
    container_name: gemini-bot
    build:
      context: .
    restart: unless-stopped
    depends_on:
      - db
    dns: 1.1.1.1
    env_file:
      - .env
    volumes:
      - ./data/bot:/data
      - ./data/cache:/cache
    tty: true

  db:
    container_name: gemini-postgres
    image: postgres:16-alpine
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data